---
- name: ensure pyenv is installed
  pacman:
    name: ['python', 'python2', 'python-pip']
  when: ansible_os_family == "Archlinux"
  become: yes

- name: ensure python is installed
  yum:
    name: ['python', 'python-pip']
  when: ansible_os_family == "RedHat"
  become: yes

- name: Install pypi libs
  pip:
    name: "{{ pypi_libs }}"
    extra_args: --user
